### ISSUE TITLE
Running Ranking.py

### ISSUE THREAD

**Issue by JTMaddux88** [ChangedNameTo/CFBPoll#3]
I have the most current version of your code and when I run the Ranking.py file it does not output the ranking like it used to. Can you check on this? Thanks.

**Comment by JTMaddux88** [comment]
The ranking.txt file is the one I am not getting after running the code.

**Comment by wn-mitch** [comment]
@JTMaddux88 I shifted the main method to a different file, I've updated the README accordingly. Thank you for the heads up! Go ahead and pull.

**Comment by JTMaddux88** [comment]
Thank you for the update. Still having an issue with it. I ran the code in the read me and am getting these errors. I'll attach a screenshot. Am I doing something  wrong? Thanks
<img width="1440" alt="Screen Shot 2019-12-04 at 11 22 02 AM" src="https://user-images.githubusercontent.com/54452708/70160426-72773600-1688-11ea-946f-3d893a2cae55.png">

**Comment by wn-mitch** [comment]
Looks to me like you're having python path issues

https://stackoverflow.com/questions/34280958/installing-numpy-on-mac-with-pip-requirements-already-satisfied-but-no-modul

I had this happen with my mac make sure you're pointing at the correct py
